---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Ensure swaywm is installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ sway__debian_packages }}"

- name: Ensure font-awesome is installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  become: true
  loop:
    - 'fonts-font-awesome'
    - 'virtualenv'
  when: sway__dynamic_names | bool

- name: Ensure terminal Packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ sway__term_pkgs }}"

- name: Ensure launcher Packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ sway__install_launcher }}"

- name: Ensure sway notification center is installed
  ansible.builtin.apt:
    name: "item"
    state: "present"
  become: true
  when: sway__notification_center | bool
  loop: "{{ sway__debian_swaync }}"
